# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'out.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 171)
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(30, 30, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.out_lineEdit = QtWidgets.QLineEdit(Form)
        self.out_lineEdit.setEnabled(True)
        self.out_lineEdit.setGeometry(QtCore.QRect(190, 30, 201, 21))
        self.out_lineEdit.setText("")
        self.out_lineEdit.setObjectName("out_lineEdit")
        self.out_toolButton = QtWidgets.QToolButton(Form)
        self.out_toolButton.setGeometry(QtCore.QRect(410, 30, 47, 21))
        self.out_toolButton.setObjectName("out_toolButton")
        self.BEFORE_pushButton = QtWidgets.QPushButton(Form)
        self.BEFORE_pushButton.setGeometry(QtCore.QRect(40, 120, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.BEFORE_pushButton.setFont(font)
        self.BEFORE_pushButton.setObjectName("BEFORE_pushButton")
        self.modtran_pushButton = QtWidgets.QPushButton(Form)
        self.modtran_pushButton.setGeometry(QtCore.QRect(300, 120, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.modtran_pushButton.setFont(font)
        self.modtran_pushButton.setObjectName("modtran_pushButton")
        self.tape5_pushButton = QtWidgets.QPushButton(Form)
        self.tape5_pushButton.setGeometry(QtCore.QRect(160, 120, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.tape5_pushButton.setFont(font)
        self.tape5_pushButton.setObjectName("tape5_pushButton")
        self.modtran_toolButton = QtWidgets.QToolButton(Form)
        self.modtran_toolButton.setGeometry(QtCore.QRect(410, 70, 47, 21))
        self.modtran_toolButton.setObjectName("modtran_toolButton")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(30, 70, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.modtran_lineEdit = QtWidgets.QLineEdit(Form)
        self.modtran_lineEdit.setEnabled(True)
        self.modtran_lineEdit.setGeometry(QtCore.QRect(190, 70, 201, 21))
        self.modtran_lineEdit.setText("")
        self.modtran_lineEdit.setObjectName("modtran_lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "运行输出"))
        self.label_34.setText(_translate("Form", "输出路径"))
        self.out_toolButton.setText(_translate("Form", "..."))
        self.BEFORE_pushButton.setText(_translate("Form", "上一页"))
        self.modtran_pushButton.setText(_translate("Form", "运行MODTRAN"))
        self.tape5_pushButton.setText(_translate("Form", "生成TAPE5"))
        self.modtran_toolButton.setText(_translate("Form", "..."))
        self.label_35.setText(_translate("Form", "MODTRAN路径"))
